version: 2
updates:
  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: weekly
      day: thursday
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: mix
    directory: "/"
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: "assent"
    schedule:
      interval: weekly
      day: thursday
    groups:
      production-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
